#ifndef ENUMS_H
#define ENUMS_H
enum _100HzStates{
  GET_GYRO,GET_MAG,ATT_UPDATE,ROT_MATRIX,GET_EULER,GET_INERTIAL,POS_VEL_PREDICTION,UPDATE_LAG_INDEX,POLL_GPS,POLL_BARO,PROCESS_CONTROL_SIGNALS,LAST_100HZ_TASK
};
#endif
